version: '3.1'
services:
  app:
    restart: always
    build: 
      context: .
      dockerfile: ./docker/application/Dockerfile
    command: bash -c "export PYTHONPATH="$PYTHONPATH:/app" && flask run --host=0.0.0.0 --port=5002"
    ports:
      - 5002:5002
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - FLASK_DEBUG=true
    volumes:
      - .:/app