version: '3.1'
services:
  db:
    restart: always
    image: postgres:12.2
    ports:
      - 5433:5433
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  app:
    restart: always
    build: 
      context: .
      dockerfile: ./docker/application/Dockerfile
    command: bash -c "export PYTHONPATH="$PYTHONPATH:/app" && alembic upgrade head && flask run --host=0.0.0.0 --port=5000"
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - FLASK_DEBUG=true
      - DB_HOST=db
      - DATABASE_URL=postgresql+psycopg2://postgres:password@db:5432/places
    volumes:
      - .:/app